#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

cd $basedir/resources/
if [ -x "update.asar" ]; then
  mv -f update.asar app.asar
  cd ..
  if [ -x "$1" ]; then
    "$@" &
  fi
fi
exit 0
