/** Tracker.doc submodule */
//---------------------------------------------------------------------------------------
Tracker.prototype.doc = {
    tooltip: {
        'miFileNew': 'New',
        'miFileOpen': 'Open [Ctrl+O]',
        'miFileSave': 'Save [Ctrl+S]',
        'miFileSaveAs': 'Save as...',
        'miEditCut': 'Cut [Ctrl+X]',
        'miEditCopy': 'Copy [Ctrl+C]',
        'miEditPaste': 'Paste [Ctrl+V]',
        'miEditClear': 'Clear [Ctrl+D]',
        'miEditUndo': 'Undo [Ctrl+Z]',
        'miEditRedo': 'Redo [Ctrl+Y | Ctrl+Shift+Z]',
        'miStop': 'Stop [Esc]',
        'miSongPlay': 'Play song [F5]',
        'miSongPlayStart': 'Play song from start [F6]',
        'miPosPlay': 'Play position [F7]',
        'miPosPlayStart': 'Play position from start [F8]',
        'miToggleLoop': 'Toggle repeat [F11]',
        'miManager': 'Track manager [F9]',
        'miPreferences': 'Preferences [F10]',
        'miSpecialLogin': 'Login to SAA-1099\ncloud for musicians',
        'scOctave': 'Base octave [Ctrl+1...Ctrl+8]',
        'scAutoSmp': 'Auto-typed sample',
        'scAutoOrn': 'Auto-typed ornament',
        'scRowStep': 'Row-step in edit mode [- Ctrl+9 | Ctrl+0 +]',
        'btPatternCreate': 'Create a new pattern\nin length of current',
        'btPatternDelete': 'Delete the current pattern\n(and renumber others if it isn\'t last one)',
        'btPatternClean': 'Clear content of current pattern',
        'btPatternInfo': 'View summary dialog of patterns',
        'scPattern': 'Current pattern number',
        'scPatternLen': 'Current pattern length',
        'txPatternUsed': 'How many times is the pattern used',
        'txPatternTotal': 'Total number of patterns',
        'btPosCreate': 'Create an empty position\nat the end of song',
        'btPosInsert': 'Create a copy of current position\nand insert before it',
        'btPosDelete': 'Delete the current position',
        'btPosMoveUp': 'Move the current position\nbefore the previous',
        'btPosMoveDown': 'Move the current position\nafter the next one',
        'scPosCurrent': 'Actual position to play or edit [- Ctrl+Shift+Left|Right +]',
        'scPosLength': 'Current position length',
        'scPosSpeed': 'Initial speed of current position',
        'scPosRepeat': 'Position number to repeat from',
    }
};
//---------------------------------------------------------------------------------------
